### ISSUE TITLE
O projeto tera continuidade?

### ISSUE THREAD

**Issue by Well-guedes** [HenrichRB/Projeto-Kine#1]
Oi @HenrichRB Tudo bem? Gostaria de saber se esse projeto ainda está de pé e se podemos dar continuidade a ele?

**Comment by HenrichRB** [comment]
### Resposta a sua querida pergunta
Sim caro @Well-guedes , o projeto ainda está de pé e aguardo ansiosamente para darmos continuidade a ele. 

**_A força esteja conosco, avante joojs._**
